### ISSUE TITLE
Explicitly set "evm_version" to "Paris"

### ISSUE THREAD

**Issue by PaulRBerg** [simplemachine92/JBSips#12]
See [my tweet](https://twitter.com/PaulRBerg/status/1656715246851981335) and also [evmdiff.com](https://evmdiff.com) to check what chains don't support PUSH0, introduced in Solidity v0.8.20. For instance, Arbitrum doesn't support it yet.

**Comment by simplemachine92** [comment]
Just to be sure, this doesn't create any issues for a mainnet deployment, right? I'm assuming that because PUSH0 is an added instruction, we will just lack the added efficiency of PUSH0.

**Comment by PaulRBerg** [comment]
Mainnet is fine. If that's the only chain where you intend to deploy this integration, then you can keep using Shanghai.

But otherwise, I would strongly recommend targeting Paris, in spite of it being less gas efficient.

**Comment by simplemachine92** [comment]
ty for bringing awareness to this as JB goes multichain in the future, for now addressed with #14
